package com.wisedoo.bd.dataobject;

import java.util.Date;

public class CorpDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.pk_corp
     *
     * @mbg.generated
     */
    private String pkCorp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.corp_code
     *
     * @mbg.generated
     */
    private String corpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.corp_name
     *
     * @mbg.generated
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.fathercorp
     *
     * @mbg.generated
     */
    private String fathercorp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.corp_type
     *
     * @mbg.generated
     */
    private String corpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.vsection
     *
     * @mbg.generated
     */
    private String vsection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.saleaddr
     *
     * @mbg.generated
     */
    private String saleaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.postaddr
     *
     * @mbg.generated
     */
    private String postaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.zipcode
     *
     * @mbg.generated
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.linkman1
     *
     * @mbg.generated
     */
    private String linkman1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.linkman2
     *
     * @mbg.generated
     */
    private String linkman2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.linkman3
     *
     * @mbg.generated
     */
    private String linkman3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.phone1
     *
     * @mbg.generated
     */
    private String phone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.phone2
     *
     * @mbg.generated
     */
    private String phone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.phone3
     *
     * @mbg.generated
     */
    private String phone3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.email1
     *
     * @mbg.generated
     */
    private String email1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.email2
     *
     * @mbg.generated
     */
    private String email2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.email3
     *
     * @mbg.generated
     */
    private String email3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.legalbodycode
     *
     * @mbg.generated
     */
    private String legalbodycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.pk_industry
     *
     * @mbg.generated
     */
    private String pkIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.begindate
     *
     * @mbg.generated
     */
    private String begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.enddate
     *
     * @mbg.generated
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.sealeddate
     *
     * @mbg.generated
     */
    private String sealeddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.isseal
     *
     * @mbg.generated
     */
    private Boolean isseal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.creationtime
     *
     * @mbg.generated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.modifiedtime
     *
     * @mbg.generated
     */
    private Date modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.ts
     *
     * @mbg.generated
     */
    private Date ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_corp.dr
     *
     * @mbg.generated
     */
    private Boolean dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.pk_corp
     *
     * @return the value of bd_corp.pk_corp
     *
     * @mbg.generated
     */
    public String getPkCorp() {
        return pkCorp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.pk_corp
     *
     * @param pkCorp the value for bd_corp.pk_corp
     *
     * @mbg.generated
     */
    public void setPkCorp(String pkCorp) {
        this.pkCorp = pkCorp == null ? null : pkCorp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.corp_code
     *
     * @return the value of bd_corp.corp_code
     *
     * @mbg.generated
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.corp_code
     *
     * @param corpCode the value for bd_corp.corp_code
     *
     * @mbg.generated
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.corp_name
     *
     * @return the value of bd_corp.corp_name
     *
     * @mbg.generated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.corp_name
     *
     * @param corpName the value for bd_corp.corp_name
     *
     * @mbg.generated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.fathercorp
     *
     * @return the value of bd_corp.fathercorp
     *
     * @mbg.generated
     */
    public String getFathercorp() {
        return fathercorp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.fathercorp
     *
     * @param fathercorp the value for bd_corp.fathercorp
     *
     * @mbg.generated
     */
    public void setFathercorp(String fathercorp) {
        this.fathercorp = fathercorp == null ? null : fathercorp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.corp_type
     *
     * @return the value of bd_corp.corp_type
     *
     * @mbg.generated
     */
    public String getCorpType() {
        return corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.corp_type
     *
     * @param corpType the value for bd_corp.corp_type
     *
     * @mbg.generated
     */
    public void setCorpType(String corpType) {
        this.corpType = corpType == null ? null : corpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.country
     *
     * @return the value of bd_corp.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.country
     *
     * @param country the value for bd_corp.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.region
     *
     * @return the value of bd_corp.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.region
     *
     * @param region the value for bd_corp.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.province
     *
     * @return the value of bd_corp.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.province
     *
     * @param province the value for bd_corp.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.city
     *
     * @return the value of bd_corp.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.city
     *
     * @param city the value for bd_corp.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.vsection
     *
     * @return the value of bd_corp.vsection
     *
     * @mbg.generated
     */
    public String getVsection() {
        return vsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.vsection
     *
     * @param vsection the value for bd_corp.vsection
     *
     * @mbg.generated
     */
    public void setVsection(String vsection) {
        this.vsection = vsection == null ? null : vsection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.saleaddr
     *
     * @return the value of bd_corp.saleaddr
     *
     * @mbg.generated
     */
    public String getSaleaddr() {
        return saleaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.saleaddr
     *
     * @param saleaddr the value for bd_corp.saleaddr
     *
     * @mbg.generated
     */
    public void setSaleaddr(String saleaddr) {
        this.saleaddr = saleaddr == null ? null : saleaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.postaddr
     *
     * @return the value of bd_corp.postaddr
     *
     * @mbg.generated
     */
    public String getPostaddr() {
        return postaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.postaddr
     *
     * @param postaddr the value for bd_corp.postaddr
     *
     * @mbg.generated
     */
    public void setPostaddr(String postaddr) {
        this.postaddr = postaddr == null ? null : postaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.zipcode
     *
     * @return the value of bd_corp.zipcode
     *
     * @mbg.generated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.zipcode
     *
     * @param zipcode the value for bd_corp.zipcode
     *
     * @mbg.generated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.url
     *
     * @return the value of bd_corp.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.url
     *
     * @param url the value for bd_corp.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.linkman1
     *
     * @return the value of bd_corp.linkman1
     *
     * @mbg.generated
     */
    public String getLinkman1() {
        return linkman1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.linkman1
     *
     * @param linkman1 the value for bd_corp.linkman1
     *
     * @mbg.generated
     */
    public void setLinkman1(String linkman1) {
        this.linkman1 = linkman1 == null ? null : linkman1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.linkman2
     *
     * @return the value of bd_corp.linkman2
     *
     * @mbg.generated
     */
    public String getLinkman2() {
        return linkman2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.linkman2
     *
     * @param linkman2 the value for bd_corp.linkman2
     *
     * @mbg.generated
     */
    public void setLinkman2(String linkman2) {
        this.linkman2 = linkman2 == null ? null : linkman2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.linkman3
     *
     * @return the value of bd_corp.linkman3
     *
     * @mbg.generated
     */
    public String getLinkman3() {
        return linkman3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.linkman3
     *
     * @param linkman3 the value for bd_corp.linkman3
     *
     * @mbg.generated
     */
    public void setLinkman3(String linkman3) {
        this.linkman3 = linkman3 == null ? null : linkman3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.phone1
     *
     * @return the value of bd_corp.phone1
     *
     * @mbg.generated
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.phone1
     *
     * @param phone1 the value for bd_corp.phone1
     *
     * @mbg.generated
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.phone2
     *
     * @return the value of bd_corp.phone2
     *
     * @mbg.generated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.phone2
     *
     * @param phone2 the value for bd_corp.phone2
     *
     * @mbg.generated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.phone3
     *
     * @return the value of bd_corp.phone3
     *
     * @mbg.generated
     */
    public String getPhone3() {
        return phone3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.phone3
     *
     * @param phone3 the value for bd_corp.phone3
     *
     * @mbg.generated
     */
    public void setPhone3(String phone3) {
        this.phone3 = phone3 == null ? null : phone3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.email1
     *
     * @return the value of bd_corp.email1
     *
     * @mbg.generated
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.email1
     *
     * @param email1 the value for bd_corp.email1
     *
     * @mbg.generated
     */
    public void setEmail1(String email1) {
        this.email1 = email1 == null ? null : email1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.email2
     *
     * @return the value of bd_corp.email2
     *
     * @mbg.generated
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.email2
     *
     * @param email2 the value for bd_corp.email2
     *
     * @mbg.generated
     */
    public void setEmail2(String email2) {
        this.email2 = email2 == null ? null : email2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.email3
     *
     * @return the value of bd_corp.email3
     *
     * @mbg.generated
     */
    public String getEmail3() {
        return email3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.email3
     *
     * @param email3 the value for bd_corp.email3
     *
     * @mbg.generated
     */
    public void setEmail3(String email3) {
        this.email3 = email3 == null ? null : email3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.legalbodycode
     *
     * @return the value of bd_corp.legalbodycode
     *
     * @mbg.generated
     */
    public String getLegalbodycode() {
        return legalbodycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.legalbodycode
     *
     * @param legalbodycode the value for bd_corp.legalbodycode
     *
     * @mbg.generated
     */
    public void setLegalbodycode(String legalbodycode) {
        this.legalbodycode = legalbodycode == null ? null : legalbodycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.pk_industry
     *
     * @return the value of bd_corp.pk_industry
     *
     * @mbg.generated
     */
    public String getPkIndustry() {
        return pkIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.pk_industry
     *
     * @param pkIndustry the value for bd_corp.pk_industry
     *
     * @mbg.generated
     */
    public void setPkIndustry(String pkIndustry) {
        this.pkIndustry = pkIndustry == null ? null : pkIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.begindate
     *
     * @return the value of bd_corp.begindate
     *
     * @mbg.generated
     */
    public String getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.begindate
     *
     * @param begindate the value for bd_corp.begindate
     *
     * @mbg.generated
     */
    public void setBegindate(String begindate) {
        this.begindate = begindate == null ? null : begindate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.enddate
     *
     * @return the value of bd_corp.enddate
     *
     * @mbg.generated
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.enddate
     *
     * @param enddate the value for bd_corp.enddate
     *
     * @mbg.generated
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.sealeddate
     *
     * @return the value of bd_corp.sealeddate
     *
     * @mbg.generated
     */
    public String getSealeddate() {
        return sealeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.sealeddate
     *
     * @param sealeddate the value for bd_corp.sealeddate
     *
     * @mbg.generated
     */
    public void setSealeddate(String sealeddate) {
        this.sealeddate = sealeddate == null ? null : sealeddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.isseal
     *
     * @return the value of bd_corp.isseal
     *
     * @mbg.generated
     */
    public Boolean getIsseal() {
        return isseal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.isseal
     *
     * @param isseal the value for bd_corp.isseal
     *
     * @mbg.generated
     */
    public void setIsseal(Boolean isseal) {
        this.isseal = isseal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.memo
     *
     * @return the value of bd_corp.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.memo
     *
     * @param memo the value for bd_corp.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.creator
     *
     * @return the value of bd_corp.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.creator
     *
     * @param creator the value for bd_corp.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.creationtime
     *
     * @return the value of bd_corp.creationtime
     *
     * @mbg.generated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.creationtime
     *
     * @param creationtime the value for bd_corp.creationtime
     *
     * @mbg.generated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.modifier
     *
     * @return the value of bd_corp.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.modifier
     *
     * @param modifier the value for bd_corp.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.modifiedtime
     *
     * @return the value of bd_corp.modifiedtime
     *
     * @mbg.generated
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.modifiedtime
     *
     * @param modifiedtime the value for bd_corp.modifiedtime
     *
     * @mbg.generated
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.ts
     *
     * @return the value of bd_corp.ts
     *
     * @mbg.generated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.ts
     *
     * @param ts the value for bd_corp.ts
     *
     * @mbg.generated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_corp.dr
     *
     * @return the value of bd_corp.dr
     *
     * @mbg.generated
     */
    public Boolean getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_corp.dr
     *
     * @param dr the value for bd_corp.dr
     *
     * @mbg.generated
     */
    public void setDr(Boolean dr) {
        this.dr = dr;
    }
}