package com.wisedoo.bd.dataobject;

import java.util.Date;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.pk_user_password
     *
     * @mbg.generated
     */
    private String pkUserPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.pk_user
     *
     * @mbg.generated
     */
    private String pkUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.encrpt_password
     *
     * @mbg.generated
     */
    private String encrptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.creationtime
     *
     * @mbg.generated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.modifiedtime
     *
     * @mbg.generated
     */
    private Date modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.ts
     *
     * @mbg.generated
     */
    private Date ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user_password.dr
     *
     * @mbg.generated
     */
    private Boolean dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.pk_user_password
     *
     * @return the value of bd_user_password.pk_user_password
     *
     * @mbg.generated
     */
    public String getPkUserPassword() {
        return pkUserPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.pk_user_password
     *
     * @param pkUserPassword the value for bd_user_password.pk_user_password
     *
     * @mbg.generated
     */
    public void setPkUserPassword(String pkUserPassword) {
        this.pkUserPassword = pkUserPassword == null ? null : pkUserPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.pk_user
     *
     * @return the value of bd_user_password.pk_user
     *
     * @mbg.generated
     */
    public String getPkUser() {
        return pkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.pk_user
     *
     * @param pkUser the value for bd_user_password.pk_user
     *
     * @mbg.generated
     */
    public void setPkUser(String pkUser) {
        this.pkUser = pkUser == null ? null : pkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.encrpt_password
     *
     * @return the value of bd_user_password.encrpt_password
     *
     * @mbg.generated
     */
    public String getEncrptPassword() {
        return encrptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.encrpt_password
     *
     * @param encrptPassword the value for bd_user_password.encrpt_password
     *
     * @mbg.generated
     */
    public void setEncrptPassword(String encrptPassword) {
        this.encrptPassword = encrptPassword == null ? null : encrptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.creator
     *
     * @return the value of bd_user_password.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.creator
     *
     * @param creator the value for bd_user_password.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.creationtime
     *
     * @return the value of bd_user_password.creationtime
     *
     * @mbg.generated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.creationtime
     *
     * @param creationtime the value for bd_user_password.creationtime
     *
     * @mbg.generated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.modifier
     *
     * @return the value of bd_user_password.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.modifier
     *
     * @param modifier the value for bd_user_password.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.modifiedtime
     *
     * @return the value of bd_user_password.modifiedtime
     *
     * @mbg.generated
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.modifiedtime
     *
     * @param modifiedtime the value for bd_user_password.modifiedtime
     *
     * @mbg.generated
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.ts
     *
     * @return the value of bd_user_password.ts
     *
     * @mbg.generated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.ts
     *
     * @param ts the value for bd_user_password.ts
     *
     * @mbg.generated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user_password.dr
     *
     * @return the value of bd_user_password.dr
     *
     * @mbg.generated
     */
    public Boolean getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user_password.dr
     *
     * @param dr the value for bd_user_password.dr
     *
     * @mbg.generated
     */
    public void setDr(Boolean dr) {
        this.dr = dr;
    }
}