package com.wisedoo.project.dao.bd;

import com.wisedoo.project.dataobject.bd.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pkUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user
     *
     * @mbg.generated
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user
     *
     * @mbg.generated
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user
     *
     * @mbg.generated
     */
    UserDO selectByPrimaryKey(String pkUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDO record);
}