package com.wisedoo.project.dao.bd;

import com.wisedoo.project.dataobject.bd.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user_password
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pkUserPassword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user_password
     *
     * @mbg.generated
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user_password
     *
     * @mbg.generated
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user_password
     *
     * @mbg.generated
     */
    UserPasswordDO selectByPrimaryKey(String pkUserPassword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user_password
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_user_password
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPasswordDO record);
}